### ISSUE TITLE
Problem with streaming files

### ISSUE THREAD

**Issue by zhujun98** [European-XFEL/karabo_data#75]
```
[zhujun@max-exfl015]~% karabo-bridge-serve-files /gpfs/exfel/exp/FXE/201830/p900023/proc/r0300 1234

Traceback (most recent call last):
  File "/home/zhujun/anaconda3/bin/karabo-bridge-serve-files", line 11, in <module>
    load_entry_point('karabo-data', 'console_scripts', 'karabo-bridge-serve-files')()
  File "/home/zhujun/karabo_data/karabo_data/export.py", line 238, in main
    serve_files(args.path, args.port)
  File "/home/zhujun/karabo_data/karabo_data/export.py", line 220, in serve_files
    data = RunDirectory(path)
  File "/home/zhujun/karabo_data/karabo_data/reader.py", line 998, in RunDirectory
    return DataCollection.from_paths(files)
  File "/home/zhujun/karabo_data/karabo_data/reader.py", line 269, in from_paths
    files = [FileAccess(h5py.File(path, 'r')) for path in paths]
  File "/home/zhujun/karabo_data/karabo_data/reader.py", line 269, in <listcomp>
    files = [FileAccess(h5py.File(path, 'r')) for path in paths]
  File "/home/zhujun/karabo_data/karabo_data/reader.py", line 143, in __init__
    tid_data = file['INDEX/trainId'].value
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/zhujun/anaconda3/lib/python3.6/site-packages/h5py/_hl/group.py", line 177, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: 'Unable to open object (component not found)'
```

**Comment by tmichela** [comment]
This looks like malformed processed file.

**Comment by takluyver** [comment]
Some of the files are empty, e.g.

```
/gpfs/exfel/exp/FXE/201830/p900023/proc/r0300/CORR-R0300-LPD05-S00000.h5 
```

This looks similar to the problem we saw with SPB recently. I've emailed Steffen about it. We might need to work around it in karabo_data, even if it's going to be fixed in the calibration pipeline.

**Comment by zhujun98** [comment]
I spoke with Steffen this afternoon. He mentioned there could be hardware reason that a module was brought down (for example two? weeks ago an LPD module was always down due to short circuit). He prefers to do nothing with such kind of case in the calibration pipeline. So we need to work around it in karabo_data.

**Comment by fangohr** [comment]
Thanks. If we ignore a missing module, we should output this somewhere. Either on the screen, or in a log file that we write routinely (problem is maybe what to call the file etc).

**Comment by takluyver** [comment]
This is causing problems for other tools that read the files as well (e.g. Cheetah crashes if it tries to read one of these files). We only know of a couple of tools (Cheetah and CASS) which actually read the files directly, so it may be solvable, but...

I'd ask Steffen if it's possible to not create the file at all under these circumstances.  I haven't tested, but I suspect tools might behave better if the files are missing completely rather than there but empty.
